---
version: '3'
services:
  powerpanel:
    container_name: powerpanel
    image: powerpanel-exporter
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    tmpfs:
      - /run
      - /tmp
    devices:
      - /dev/usb/hiddev0
...
